spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-clientid}
            client-secret: ${google-secret}
            scope: profile, email
          naver:
            client-id: ${naver.clientid}
            client-secret: ${naver-secret}
            redirect-uri: http://localhost:9999/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fortwoweek?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: sunire9850
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    view-names: th/*
  mvc:
    view:
      suffix: .jsp

mybatis:
  config: mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9999
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: none
    #ssl:
    #enabled: true
    #key-store: keystore.p12
    #key-store-password: ${key-password}
    #key-store-type: PKCS12
    #key-alias: bns-ssl

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: "bYqvOqgr/7sryvSETWjlkcS+kVb+uwWMTqgIkU6qXLRHdOmllZr1t/To74XV6Vd0jJTPCbviDKNHku3R+XZ+LQ=="
